### PR TITLE
Allow relative paths by using "hasbin" to check for executable

### PR DESCRIPTION
**Pull request by jmfederico**
Hi

I use Virtual Environments a lot in python, and having atom use yapf from the active virtualenv can be done by just executing from PATH using relative paths.

I use hasbin node package to detect if the bin is accesible or not.

### CODE REVIEW

**Comment by blacktop** [comment]
I'm very sorry to have taken so long to review this Pull Request.  I will test and merge if no issues by the end of the day.  Thank you for contributing.

**Comment by jmfederico** [comment]
Hi, is there anything I can do to help you test this?

**Comment by jmfederico** [comment]
I proposed the [same change](https://github.com/lexicalunit/atom-isort/pull/1) to [atom-isort](https://github.com/lexicalunit/atom-isort/) project in case you want't to see it in use.

**Comment by blacktop** [comment]
If it is good enough for @lexicalunit then it is good enough for me. 😁

**Comment by blacktop** [comment]
I have pushed this out to atom.io  

I appologize for the long delay and thank you for your help @jmfederico  👍

**Pull request merged**
